# Generated by Django 6.0 on 2025-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo_pay', 'MoMo Pay'), ('tigo_cash', 'Tigo Cash'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
