# Generated by Django 6.0 on 2025-03-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo_pay', 'MoMo Pay'), ('tigo_cash', 'Tigo Cash'), ('bank_transfer', 'Bank Transfer'), ('balance', 'Balance')], max_length=50),
        ),
    ]
