# Generated by Django 5.1.6 on 2025-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_maintenancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
