# Generated by Django 6.0 on 2025-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube Video URL')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOTAL_EARNINGS', 'Total earnings'), ('TOTAL_WITHDRAWALS', 'Total Withdrawals'), ('REFERRAL_EARNINGS', 'Referral earnings'), ('RETAIL_BONUS', 'Retail Bonus'), ('LEADERSHIP_BONUS', 'Leadership bonus'), ('MATCHING_BONUS', 'Matching bonus'), ('TOTAL_EXPENSES', 'Total expenses')], max_length=20),
        ),
    ]
