# Generated by Django 6.0 on 2025-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adminnews_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
