# Generated by Django 6.0 on 2025-03-02 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_adminnews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='left_leg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_referral', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Starter', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='right_leg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_referral', to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
