# Generated by Django 5.1.6 on 2025-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_left_leg_userprofile_maintenance_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('review', 'Review')], default='inactive', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('diamond', 'Diamond')], default='Starter', max_length=20),
        ),
    ]
