# Generated by Django 5.1.6 on 2025-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_status_alter_userprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
