# Generated by Django 5.1.6 on 2025-03-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_referral_bonus_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matching_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
