# Generated by Django 5.1.6 on 2025-03-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile_matching_bonus_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='matching_bonus_awarded',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matching_pairs_count',
            field=models.IntegerField(default=0),
        ),
    ]
