# Generated by Django 5.1.6 on 2025-03-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userprofile_matching_bonus_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='placement_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
