# Generated by Django 5.1.6 on 2025-03-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_placement_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='placement_assigned',
        ),
    ]
