# Generated by Django 5.1.6 on 2025-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOTAL_EARNINGS', 'Total earnings'), ('TOTAL_WITHDRAWALS', 'Total Withdrawals'), ('REFERRAL_EARNINGS', 'Referral earnings'), ('RETAIL_BONUS', 'Retail Bonus'), ('LEADERSHIP_BONUS', 'Leadership bonus'), ('MATCHING_BONUS', 'Matching bonus'), ('TOTAL_EXPENSES', 'Total expenses'), ('BALANCE', 'Balance')], max_length=20),
        ),
    ]
