# Generated by Django 5.1.6 on 2025-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maintenance_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
