# Generated by Django 5.1.6 on 2025-03-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userprofile_maintenance_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='direct_referrals_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='generations_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='left_leg_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='right_leg_count',
        ),
    ]
