# Generated by Django 5.1.6 on 2025-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_userprofile_direct_referrals_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
