# Generated by Django 5.1.6 on 2025-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofile_activation_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maintenance_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
