# Generated by Django 5.1.6 on 2025-03-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_user_maintenance_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_paid_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_paid_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maintenance_due_date',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
