# Generated by Django 5.1.6 on 2025-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_userprofile_activation_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='maintenance_fee',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maintenance_paid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maintenance_paid_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maintenance_paid_date',
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='maintenance_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
