# Generated by Django 5.1.6 on 2025-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_userprofile_maintenance_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('review', 'Review'), ('suspend', 'Suspend')], default='inactive', max_length=8),
        ),
    ]
