# Generated by Django 5.1.6 on 2025-03-11 18:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0020_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cached_downline_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='activationfeeproof',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOTAL_EARNINGS', 'Total earnings'), ('TOTAL_WITHDRAWALS', 'Total Withdrawals'), ('REFERRAL_EARNINGS', 'Referral earnings'), ('RETAIL_BONUS', 'Retail Bonus'), ('LEADERSHIP_BONUS', 'Leadership bonus'), ('MATCHING_BONUS', 'Matching bonus'), ('TOTAL_EXPENSES', 'Total expenses'), ('BALANCE', 'Balance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+25078xxxxxxx'.", regex='\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('review', 'Review'), ('suspend', 'Suspend')], db_index=True, default='inactive', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='myapp_user_usernam_45e227_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='myapp_user_email_5d02ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='myapp_user_phone_n_38d3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='myapp_user_status_9c4f0c_idx'),
        ),
    ]
