# Generated by Django 5.1.6 on 2025-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('kenya', 'Kenya'), ('uganda', 'Uganda'), ('drc', 'DRC'), ('tanzania', 'Tanzania')], db_index=True, default='rwanda', max_length=20),
        ),
    ]
