# Generated by Django 5.1.6 on 2025-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0024_alter_user_country'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country'], name='myapp_user_country_b53529_idx'),
        ),
    ]
