# Generated by Django 5.2.1 on 2025-06-07 19:59

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=products.models.MediaStorage(), upload_to='products/'),
        ),
    ]
